import { Language, ParameterMeta } from './types';

export const PARAM_CONFIGS: ParameterMeta[] = [
  {
    key: 'do',
    name: {
      en: 'Dissolved Oxygen',
      te: 'కరిగిన ఆక్సిజన్',
      hi: 'घुली ऑक्सीजन',
    },
    unit: 'mg/L',
    minDisplay: 0,
    maxDisplay: 12,
    safeMin: 5.0,
    safeMax: 12.0,
    critLow: 3.0,
    critHigh: 999,
    color: 'from-cyan-500 to-blue-600',
    accentHex: '#06b6d4',
    description: {
      en: 'Vital for fish respiration. Must stay above 5.0 mg/L; drops below 3.0 mg/L cause suffocation.',
      te: 'చేపల శ్వాసక్రియకు అత్యంత ముఖ్యం. 5.0 mg/L కంటే ఎక్కువగా ఉండాలి.',
      hi: 'मछलियों के सांस लेने के लिए महत्वपूर्ण। 5.0 mg/L से ऊपर होना चाहिए।',
    },
    icon: 'Waves',
  },
  {
    key: 'temperature',
    name: {
      en: 'Water Temperature',
      te: 'నీటి ఉష్ణోగ్రత',
      hi: 'पानी का तापमान',
    },
    unit: '°C',
    minDisplay: 15,
    maxDisplay: 40,
    safeMin: 26.0,
    safeMax: 32.0,
    critLow: 22.0,
    critHigh: 35.0,
    color: 'from-amber-500 to-orange-600',
    accentHex: '#f59e0b',
    description: {
      en: 'Governs biological metabolic rates and oxygen retention. Ideal tropical range is 26°C - 32°C.',
      te: 'చేపల జీర్ణక్రియను ప్రభావితం చేస్తుంది. అనుకూలమైన పరిధి 26°C - 32°C.',
      hi: 'मेटाबॉलिज्म को नियंत्रित करता है। आदर्श सीमा 26°C - 32°C है।',
    },
    icon: 'Thermometer',
  },
  {
    key: 'ph',
    name: {
      en: 'Water pH Level',
      te: 'నీటి pH స్థాయి',
      hi: 'पानी का pH स्तर',
    },
    unit: 'pH',
    minDisplay: 4,
    maxDisplay: 11,
    safeMin: 6.5,
    safeMax: 8.5,
    critLow: 6.0,
    critHigh: 9.0,
    color: 'from-emerald-400 to-teal-600',
    accentHex: '#10b981',
    description: {
      en: 'Acid/alkaline balance. Outside 6.5 - 8.5 causes mucosal damage and amplifies ammonia toxicity.',
      te: 'ఆమ్ల-క్షార సమతుల్యత. 6.5 నుండి 8.5 మధ్య ఉండడం శ్రేయస్కరం.',
      hi: 'अम्ल-क्षार संतुलन। 6.5 से 8.5 के बीच का स्तर सुरक्षित माना जाता है।',
    },
    icon: 'Activity',
  },
  {
    key: 'ammonia',
    name: {
      en: 'Un-ionized Ammonia (NH₃)',
      te: 'అమ్మోనియా శాతం',
      hi: 'अमोनिया स्तर',
    },
    unit: 'mg/L',
    minDisplay: 0,
    maxDisplay: 2.5,
    safeMin: 0.0,
    safeMax: 0.5,
    critLow: -999,
    critHigh: 1.0,
    color: 'from-rose-500 to-red-700',
    accentHex: '#f43f5e',
    description: {
      en: 'Toxic waste from decomposed uneaten feed & excretion. Levels > 0.5 mg/L inflict acute organ damage.',
      te: 'మిగిలిపోయిన ఆహారం మరియు వ్యర్థాల వల్ల ఏర్పడే విషపూరిత వాయువు. 0.5 mg/L కంటే తక్కువగా ఉండాలి.',
      hi: 'बचे हुए चारे व अपशिष्ट से उत्पन्न जहरीला तत्व। 0.5 mg/L से नीचे रहना चाहिए।',
    },
    icon: 'AlertTriangle',
  },
  {
    key: 'turbidity',
    name: {
      en: 'Water Turbidity',
      te: 'నీటి మడ్డి / టర్బిడిటీ',
      hi: 'पानी का गंदलापन',
    },
    unit: 'NTU',
    minDisplay: 0,
    maxDisplay: 160,
    safeMin: 10,
    safeMax: 60,
    critLow: -999,
    critHigh: 100,
    color: 'from-indigo-500 to-purple-600',
    accentHex: '#8b5cf6',
    description: {
      en: 'Suspended solids and algae density. Levels > 60 NTU reduce photosynthetic sunlight penetration.',
      te: 'నీటిలో తేలియాడే మట్టి మరియు ఆల్గే సాంద్రత. 60 NTU కంటే తక్కువగా ఉండాలి.',
      hi: 'पानी में घुली मिट्टी या काई। 60 NTU से कम होना चाहिए।',
    },
    icon: 'Droplets',
  },
];

export const FAULT_DESCRIPTIONS = [
  {
    id: 'low_oxygen',
    title: {
      en: 'Oxygen Depletion / Aerator Failure',
      te: 'ఆక్సిజన్ పతనం / ఏరేటర్ పనిచేయకపోవడం',
      hi: 'ऑक्सीजन की भारी कमी / एयरेटर विफलता',
    },
    effect: 'DO drops rapidly (-4.2 mg/L)',
    icon: 'Wind',
    badge: 'Critical Hypoxia',
    color: 'from-cyan-600/30 to-blue-900/40 border-cyan-500/40 text-cyan-400',
  },
  {
    id: 'ammonia_spike',
    title: {
      en: 'Ammonia Spike (Overfeeding Surge)',
      te: 'అధిక అమ్మోనియా వ్యాప్తి (అధిక మేత)',
      hi: 'अमोनिया स्पाइक (अत्यधिक चारा अपशिष्ट)',
    },
    effect: 'Ammonia surges (+1.6 mg/L)',
    icon: 'AlertOctagon',
    badge: 'Toxic Hazard',
    color: 'from-rose-600/30 to-red-900/40 border-rose-500/40 text-rose-400',
  },
  {
    id: 'heatwave',
    title: {
      en: 'Diurnal Thermal Shock / Heatwave',
      te: 'ఎండ తీవ్రత / నీటి ఉష్ణోగ్రత పెరుగుదల',
      hi: 'तेज गर्मी / तापमान में अचानक वृद्धि',
    },
    effect: 'Temp surges (+6.5 °C)',
    icon: 'Flame',
    badge: 'Thermal Shock',
    color: 'from-amber-600/30 to-orange-900/40 border-amber-500/40 text-amber-400',
  },
  {
    id: 'ph_crash',
    title: {
      en: 'Acid Rain / Sudden pH Crash',
      te: 'ఆమ్ల వర్షం / pH హఠాత్తు పతనం',
      hi: 'अम्लीय वर्षा / pH का अचानक गिरना',
    },
    effect: 'pH plummets (-1.8)',
    icon: 'ShieldAlert',
    badge: 'Acidosis Risk',
    color: 'from-teal-600/30 to-emerald-900/40 border-teal-500/40 text-teal-400',
  },
  {
    id: 'turbidity_surge',
    title: {
      en: 'Heavy Runoff / Algal Bloom Surge',
      te: 'భారీ వర్షపు బురద / ఆల్గే వ్యాప్తి',
      hi: 'मिट्टी का बहाव / भारी शैवाल फैलाव',
    },
    effect: 'Turbidity spikes (+95 NTU)',
    icon: 'EyeOff',
    badge: 'Light Blockage',
    color: 'from-purple-600/30 to-indigo-900/40 border-purple-500/40 text-purple-400',
  },
];

export const UI_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    systemTitle: 'AquaSentinel AI',
    systemTagline: 'Intelligent Aquaculture Water-Quality & Fish Welfare Command Center',
    livePond: 'Active Pond #01 - Freshwater Tilapia & Shrimp',
    healthScore: 'Pond Health Index',
    statusSafe: 'Optimal Condition',
    statusWatch: 'Warning Watch',
    statusDanger: 'Critical Danger',
    isolationForest: 'Isolation Forest ML Anomaly Engine',
    mlNominal: 'Multi-parametric pattern nominal',
    mlAnomaly: 'Unusual correlation anomaly flagged',
    historicalTrends: 'Pond Telemetry & Circadian Dynamics',
    digitalTwin: 'Digital Twin Pond Simulation',
    simulationStudio: 'Emergency Simulation Lab & IoT Ingestion',
    alertAudit: 'Real-Time Alert Feed & Incident Log',
    aiAdvisory: 'AquaSentinel AI Advisory & Agronomist',
    askQuestionPlaceholder: 'Ask aquaculture AI about water treatment, aeration, feed reduction...',
    sendPrompt: 'Ask Copilot',
    refresh: 'Refresh',
    exportReport: 'Export Telemetry',
    connected: 'Telemetry Online',
    reconnecting: 'Reconnecting...',
    safeZone: 'Safe Target Zone',
    criticalLimit: 'Critical Threshold',
    predictedTrend: 'Predictive ETA Warning',
    noAlerts: 'No critical anomalies detected in the last cycle.',
    injectFault: 'Simulate Incident',
    injectSuccess: 'Incident condition dispatched to engine',
    manualIngest: 'Manual Telemetry Ingestion (ESP32/LoRa Test)',
    submitting: 'Transmitting...',
    diurnalDawn: 'Dawn (Algal Respiration Low DO)',
    diurnalNoon: 'Midday Peak Sun (Maximum Photosynthesis)',
    diurnalDusk: 'Dusk (Temperature Cooling)',
    diurnalNight: 'Night Watch (Critical Oxygen Consumption)',
  },
  te: {
    systemTitle: 'ఆక్వాసెంటినెల్ AI',
    systemTagline: 'ఆక్వా చెరువుల నీటి నాణ్యత మరియు చేపల/రొయ్యల ఆరోగ్య పర్యవేక్షణ వ్యవస్థ',
    livePond: 'లైవ్ చెరువు #01 - రొయ్యలు & చేపల పెంపకం',
    healthScore: 'చెరువు ఆరోగ్య సూచిక',
    statusSafe: 'సురక్షిత స్థితి',
    statusWatch: 'హెచ్చరిక గమనిక',
    statusDanger: 'తీవ్ర ప్రమాద స్థాయి',
    isolationForest: 'ఐసోలేషన్ ఫారెస్ట్ ML అసాధారణ గుర్తింపు ఇంజిన్',
    mlNominal: 'సెన్సార్ తీరు సాధారణంగా ఉంది',
    mlAnomaly: 'అసాధారణ మార్పులు గుర్తించబడ్డాయి',
    historicalTrends: 'నీటి చరిత్ర & గ్రాఫ్ వివరాలు',
    digitalTwin: 'డిజిటల్ ట్విన్ చెరువు ప్రత్యక్ష దృశ్యం',
    simulationStudio: 'ఎమర్జెన్సీ అనుకరణ & సెన్సార్ పరీక్షా కేంద్రం',
    alertAudit: 'హెచ్చరికల లాగ్ & సంఘటనల రికార్డు',
    aiAdvisory: 'ఆక్వాసెంటినెల్ AI నిపుణుల సలహాలు',
    askQuestionPlaceholder: 'ఏరేటర్ల సమయం, సున్నం వేయడం, మేత నియంత్రణపై అడగండి...',
    sendPrompt: 'సలహా అడగండి',
    refresh: 'రిఫ్రెష్',
    exportReport: 'డేటా ఎగుమతి',
    connected: 'కనెక్ట్ అయింది',
    reconnecting: 'పునఃసంధానం...',
    safeZone: 'సురక్షిత పరిధి',
    criticalLimit: 'ప్రమాద పరిధి',
    predictedTrend: 'ముందస్తు అంచనా హెచ్చరిక',
    noAlerts: 'గత సైకిల్‌లో ఎటువంటి ప్రమాదాలు లేవు.',
    injectFault: 'పరిస్థితిని ప్రేరేపించండి',
    injectSuccess: 'ఇంజిన్‌కు ఆదేశం విజయవంతంగా పంపబడింది',
    manualIngest: 'మాన్యువల్ సెన్సార్ డేటా నమోదు (ESP32 పరీక్ష)',
    submitting: 'పంపుతోంది...',
    diurnalDawn: 'వేకువజాము (ఆక్సిజన్ తక్కువగా ఉండే సమయం)',
    diurnalNoon: 'మధ్యాహ్న సమయం (గరిష్ట ఆక్సిజన్ ఉత్పత్తి)',
    diurnalDusk: 'సాయంత్రం (ఉష్ణోగ్రత తగ్గే సమయం)',
    diurnalNight: 'రాత్రి సమయం (ఆక్సిజన్ పర్యవేక్షణ అత్యవసరం)',
  },
  hi: {
    systemTitle: 'एक्वासेंटिनल AI',
    systemTagline: 'मत्स्य पालन जल गुणवत्ता एवं मछली स्वास्थ्य निगरानी तंत्र',
    livePond: 'सक्रिय तालाब #01 - मीठे पानी का मत्स्य पालन',
    healthScore: 'तालाब स्वास्थ्य सूचकांक',
    statusSafe: 'उत्कृष्ट स्थिति',
    statusWatch: 'चेतावनी निगरानी',
    statusDanger: 'गंभीर संकट स्थिति',
    isolationForest: 'आइसोलेशन फॉरेस्ट AI विसंगति पहचान इंजन',
    mlNominal: 'सभी पैरामीटर सामान्य पैटर्न में हैं',
    mlAnomaly: 'असामान्य बहु-पैरामीटर बदलाव का संकेत',
    historicalTrends: 'जल गुणवत्ता इतिहास एवं समय चक्र ग्राफ',
    digitalTwin: 'डिजिटल ट्विन तालाब सिमुलेशन',
    simulationStudio: 'आपातकालीन सिमुलेशन एवं सेंसर जांच केंद्र',
    alertAudit: 'सक्रिय चेतावनी लॉग व घटनाक्रम',
    aiAdvisory: 'एक्वासेंटिनल AI विशेषज्ञ सलाह',
    askQuestionPlaceholder: 'एयरेटर चलाने, अमोनिया घटाने, चूना डालने पर पूछें...',
    sendPrompt: 'सलाह लें',
    refresh: 'रिफ्रेश',
    exportReport: 'डेटा डाउनलोड',
    connected: 'कनेक्टेड',
    reconnecting: 'पुनः कनेक्ट कर रहे हैं...',
    safeZone: 'सुरक्षित सीमा',
    criticalLimit: 'खतरे की सीमा',
    predictedTrend: 'पूर्वानुमानित चेतावनी',
    noAlerts: 'पिछले चक्र में कोई गंभीर समस्या नहीं पाई गई।',
    injectFault: 'समस्या का सिमुलेशन करें',
    injectSuccess: 'इंजन को सिमुलेशन निर्देश भेजा गया',
    manualIngest: 'मैन्युअल सेंसर डेटा प्रविष्टि (ESP32/LoRa टेस्ट)',
    submitting: 'भेज रहे हैं...',
    diurnalDawn: 'भोर (ऑक्सीजन का न्यूनतम स्तर)',
    diurnalNoon: 'दोपहर (अधिकतम धूप व प्रकाश संश्लेषण)',
    diurnalDusk: 'शाम (तापमान में गिरावट)',
    diurnalNight: 'रात (ऑक्सीजन निगरानी का महत्वपूर्ण समय)',
  },
};
